// src/app/shared/components/button/button.component.ts
import { Component, computed, input } from '@angular/core';

type ButtonVariant = 'primary' | 'outline' | 'ghost';
type ButtonSize = 'sm' | 'md' | 'lg';

@Component({
    selector: 'button[app-button], a[app-button]',
    standalone: true,
    template: '<ng-content></ng-content>',
    host: {
        'class': 'inline-flex items-center justify-center rounded-full font-medium transition-all focus:outline-none focus:ring-2 focus:ring-spring-iris focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none active:scale-95 cursor-pointer',
        '[class]': 'dynamicClasses()'
    }
})
export class ButtonComponent {
    variant = input<ButtonVariant>('primary');
    size = input<ButtonSize>('md');
    fullWidth = input<boolean | string>(false); // Handle boolean attribute

    private variants: Record<ButtonVariant, string> = {
        primary: "bg-spring-iris text-white hover:bg-violet-700 shadow-sm shadow-spring-iris/30",
        outline: "border border-spring-iris text-spring-iris hover:bg-spring-iris/5",
        ghost: "text-brand-700 hover:bg-brand-50 hover:text-brand-800",
    };

    private sizes: Record<ButtonSize, string> = {
        sm: "h-9 px-4 text-sm",
        md: "h-11 px-6 text-base",
        lg: "h-14 px-8 text-lg",
    };

    protected dynamicClasses = computed(() => {
        const isFull = this.fullWidth() === '' || this.fullWidth() === 'true' || this.fullWidth() === true;
        return `${this.variants[this.variant()]} ${this.sizes[this.size()]} ${isFull ? 'w-full' : ''}`;
    });
}

// components/Button.tsx
import React from 'react';
import { cn } from '../utils/cn';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'outline' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  fullWidth?: boolean;
}

export const Button: React.FC<ButtonProps> = ({ 
  children, 
  className, 
  variant = 'primary', 
  size = 'md', 
  fullWidth = false,
  ...props 
}) => {
  
  const variants = {
    // Changed to spring-iris (Purple) for a more unique, psychology-focused look
    primary: "bg-spring-iris text-white hover:bg-violet-700 shadow-sm shadow-spring-iris/30",
    outline: "border border-spring-iris text-spring-iris hover:bg-spring-iris/5",
    ghost: "text-brand-700 hover:bg-brand-50 hover:text-brand-800",
  };

  const sizes = {
    sm: "h-9 px-4 text-sm",
    md: "h-11 px-6 text-base",
    lg: "h-14 px-8 text-lg",
  };

  return (
    <button 
      className={cn(
        "inline-flex items-center justify-center rounded-full font-medium transition-all focus:outline-none focus:ring-2 focus:ring-spring-iris focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none active:scale-95",
        variants[variant],
        sizes[size],
        fullWidth && "w-full",
        className
      )} 
      {...props}
    >
      {children}
    </button>
  );
};
